drop function usun_sprzet(integer);
drop trigger dodaj_kare on rezerwacje_pokoje;
drop function dodaj_kare();
drop function oblicz_znizke(integer, numeric, date);
drop table if exists email_hash cascade;
drop table if exists usl_rez;
drop table if exists uslugi_dod;
drop table if exists kary;
drop table if exists platnosci;
drop table if exists pokoje_wyposazenie;
drop table if exists wyposazenie;
drop table if exists rodzaje_wyposazenia;
drop table if exists rezerwacje_pokoje cascade;
drop table if exists rezerwacje_goscie;
drop table if exists goscie;
drop table if exists pokoje;
